//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 20.01.2021 11:57:10
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace DocumentManager.DAL.Model
{
    /// <summary>
    /// Файлов тип: jpg,  pdf, xml, word, xsl...
    /// </summary>
    public partial class FileType {

        public FileType()
        {
            this.Documents = new List<Document>();
            OnCreated();
        }

        /// <summary>
        /// Код на файлов тип: jpg,  pdf, xml, word, xsl...
        /// </summary>
        public virtual string FileTypeCode { get; set; }

        /// <summary>
        /// Наименование
        /// </summary>
        public virtual string Name { get; set; }

        public virtual IList<Document> Documents { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
