//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 20.01.2021 11:57:10
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace DocumentManager.DAL.Model
{
    public partial class DocumentApplication {

        public DocumentApplication()
        {
            OnCreated();
        }

        public virtual long DocumentID { get; set; }

        public virtual long ApplicationID { get; set; }

        public virtual string ApplicationSigningTypeCode { get; set; }

        public virtual bool CanBeModified { get; set; }

        public virtual bool HasError { get; set; }

        public virtual string ErrorComment { get; set; }

        public virtual bool IsOriginalReceived { get; set; }

        public virtual DateTime? DateNotification { get; set; }

        public virtual bool? IsFromClientPortal { get; set; }

        public virtual Document Document { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
